; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{953A8B64-1C04-49BA-B21D-9E972658C83D}
AppName=Trash Attack x64
AppVersion=1.0
;AppVerName=Trash Attack x64 1.0
AppPublisher=K9
DefaultDirName={pf}\Trash Attack x64
DisableProgramGroupPage=yes
OutputDir=C:\Users\kalps\OneDrive\Documents\Unity Projects\Personal Project Game #1\Builds\Windows\Installer
OutputBaseFilename=Trash Attack Setup (x64)
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\kalps\OneDrive\Documents\Unity Projects\Personal Project Game #1\Builds\Windows\x86_64\Trash Attack.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\kalps\OneDrive\Documents\Unity Projects\Personal Project Game #1\Builds\Windows\x86_64\Mono\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\kalps\OneDrive\Documents\Unity Projects\Personal Project Game #1\Builds\Windows\x86_64\Trash Attack_Data\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\kalps\OneDrive\Documents\Unity Projects\Personal Project Game #1\Builds\Windows\x86_64\UnityCrashHandler64.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\kalps\OneDrive\Documents\Unity Projects\Personal Project Game #1\Builds\Windows\x86_64\UnityPlayer.dll"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{commonprograms}\Trash Attack x64"; Filename: "{app}\Trash Attack.exe"
Name: "{commondesktop}\Trash Attack x64"; Filename: "{app}\Trash Attack.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\Trash Attack.exe"; Description: "{cm:LaunchProgram,Trash Attack x64}"; Flags: nowait postinstall skipifsilent

